/**
 * Created by banlan002 on 2017/7/21.
 */
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const RECIVER_SUPPLIERS = "RECIVER_SUPPLIERS";
export const RECIVER_LOCATIONS = "RECIVER_LOCATIONS";
export const RECIVER_DICT_COLORS = "RECIVER_DICT_COLORS";
export const RECIVER_DICT_STYLES = "RECIVER_DICT_STYLES";
export const RECIVER_DICT_CATEGORIES = "RECIVER_DICT_CATEGORIES";
export const RECIVER_DICT_SORTS = "RECIVER_DICT_SORTS";
export const RECIVER_DICT_ROOM_TYPES = "RECIVER_DICT_ROOM_TYPES";
export const RECIVER_DICT_HOUSE_TYPES = "RECIVER_DICT_HOUSE_TYPES";
export const RECIVER_DICT_STRUCTURES = "RECIVER_DICT_STRUCTURES";
export const RECIVER_DICT_PLAN_STATUS_LIST = "RECIVER_DICT_PLAN_STATUS_LIST";
export const RECIVER_DICT_DETAILED_LIST_STATES =
  "RECIVER_DICT_DETAILED_LIST_STATES";
export const RECIVER_DICT_ORDER_STATES = "RECIVER_DICT_ORDER_STATES";
export const RECIVER_DICT_PRODUCT_STATES = "RECIVER_DICT_PRODUCT_STATES";
export const RECIVER_DICT_USER_GROUPS = "RECIVER_DICT_USER_GROUPS";
export const RECIVER_DICT_QUOTED_RATES = "RECIVER_DICT_QUOTED_RATES";
export const RECIVER_DICT_BACK_CHOICES = "RECIVER_DICT_BACK_CHOICES";
export const RECIVER_MESSAGE_NUM = "RECIVER_MESSAGE_NUM";

//===========================================================

export const GET_HEIGHT_BODY = "GET_HEIGHT_BODY";
export const GET_FACTORY_USER = "GET_FACTORY_USER";
